{% set name = 'browndye' %}
# Browndye uses date-based versioning
# but tags use English formatting
{% set version = "2023.12.29" %}
{% set tag = "29-Dec-2023" %}
{% set build = 0 %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  fn: {{ name }}.tar.gz
  url: https://bitbucket.org/gahuber95/browndye2/get/{{ tag }}.tar.gz
  sha256: 26bc70959d9c19f0e3b64c1613eac03b88e377212bbd308c56afc8b930985c14
  patches:
    - makefile-env.patch

build:
  number: {{ build }}
  # win: not supported
  # osx: requires apbs, not packaged for osx
  skip: true  # [win or osx]

requirements:
  build:
    - binutils
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - ocaml
  host:
    - expat
    - liblapack
  run:
    - apbs

test:
  requires:
    - make
  source_files:
    - browndye2/examples

about:
  home: https://browndye.ucsd.edu
  license: MIT
  license_family: MIT
  license_file: browndye2/COPYRIGHT
  summary: Brownian Dynamics of Biological Molecules
  doc_url: https://browndye.ucsd.edu/documentation.html
  dev_url: https://bitbucket.org/gahuber95/browndye2/

extra:
  recipe-maintainers:
    - minrk
